# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod verify
builds:
  -
    id: "und"
    binary: und
    main: ./cmd/und
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=UndMainchain
      - -X github.com/cosmos/cosmos-sdk/version.AppName=und
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.FullCommit}}
      - -X github.com/tendermint/tendermint/version.TMCoreSemVer={{.Env.TM_CORE_SEM_VERSION}}
      - -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo"
    flags:
      - -mod=readonly
      - -tags="netgo"
    hooks:
      pre: go mod verify

archives:
  -
    id: "und"
    builds:
      - und
    name_template: >-
      {{ .Binary }}_v
      {{ .Version }}_
      {{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
    format: tar.gz

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^build:'
      - '^dist:'
