version: "3"
services:
  dn_node1:
    build:
      args:
        WITH_DELVE: "yes"
    security_opt:
      - seccomp:unconfined # required for running through delve
    command: /root/.go/bin/dlv --listen=:40000 --headless=true --api-version=2 exec /root/.go/bin/und start -- --home /root/.und_mainchain/node1
    ports:
      - "26661:26661"
      - "26651:26651"
      - "40000:40000"
      - "1317:1317"
      - "9090:9090"
    expose:
      - 40000
