version: "3"
services:
  dn_node1:
    hostname: dn_node1
    build:
      context: ..
      dockerfile: ./Docker/validator.local/Dockerfile
      args:
        WITH_DELVE: "no"
    container_name: dn_node1
    command: /root/.go/bin/und start --home /root/.und_mainchain/node1
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.3
    ports:
      - "26661:26661"
      - "26651:26651"
      - "1317:1317"
      - "9092:9092"

  dn_node2:
    hostname: dn_node2
    build:
      context: ..
      dockerfile: ./Docker/validator.local/Dockerfile
      args:
        WITH_DELVE: "no"
    container_name: dn_node2
    command: /root/.go/bin/und start --home /root/.und_mainchain/node2
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.4
    ports:
      - "26662:26662"
      - "26652:26652"

  dn_node3:
    hostname: dn_node3
    build:
      context: ..
      dockerfile: ./Docker/validator.local/Dockerfile
      args:
        WITH_DELVE: "no"
    container_name: dn_node3
    command: /root/.go/bin/und start --home /root/.und_mainchain/node3
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.5
    ports:
      - "26663:26663"
      - "26653:26653"

  dummy:
    hostname: dummy
    build:
      context: ..
      dockerfile: ./Docker/validator.local/Dockerfile
      args:
        WITH_DELVE: "no"
    container_name: dummy
    command: /root/.go/bin/und start --home /root/.und_mainchain/dummy --p2p.laddr=tcp://0.0.0.0:26654 --rpc.laddr=tcp://0.0.0.0:26664
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.8
    ports:
      - "26664:26664"
      - "26654:26654"

  proxy:
    hostname: proxy
    build:
      context: ..
      dockerfile: ./Docker/proxy/Dockerfile
    networks:
      mainchain_devnet:
        ipv4_address: 172.25.0.7
    ports:
      - "1318:1318"
      - "9092:9092"

networks:
  mainchain_devnet:
    ipam:
      driver: default
      config:
      - subnet: 172.25.0.0/24
